### ISSUE TITLE
Does this plugin support iOS

### ISSUE THREAD

**Issue by DartLazer** [alperengozum/expo-alarm#4]
First of all, great work! It works brilliantly on our android app and we love it!

The readme is a bit confusing and contradicting:
`Use **Android AlarmClock** in React Native / Expo app`

And then it says:
```
Configure for iOS
Run npx pod-install after installing the npm package
```
Before we push it to our test build, did you test this on iOS and if so, does it work?

Thanks a lot!

**Comment by alperengozum** [comment]
Hi @DartLazer,

Thank you for your kind words and for creating an issue! I appreciate your engagement with the project.

Just to clarify, the message you encountered is a default one from Expo. I recently updated the `README.md` file to provide clearer information. Currently, this module does not support iOS because it relies on Android's Alarm Clock functionality.

Unfortunately, I don't have the time to add iOS support at the moment. However, if you're interested in developing the iOS part, please feel free to contribute! Your help would be greatly appreciated. 🚀

Best regards!

**Comment by DartLazer** [comment]
Thanks a lot! I unfortunately do not have access to any iOS devices at all!Thanks a lot and we happily keep on using yoru work!
